# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a38f9a6f6c8d938cc634f498b32ff03c0ee76c163747e6011a37452c7a095cb35c887914e0ad03d3380e94cf7d7412edf77529f8576a80c8034bfadd22a42fe6

test:
  secret_key_base: 545c1afb4bf4e6ebe3de79b0baba202ceccb0ce2bead26466a8f5cded593f4c6abe432e3d8c11244c88ee04b4d9b98cfb7ff1bbd5d2e5f926d5ed962fbb51b2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
